apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "roche-siem-agent.fullname" . }}-config
  labels:
    {{- include "roche-siem-agent.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.config }}
  {{ $k }}: "{{ $v }}"
{{- end }}
